Numbers: random numbers facts
molybdenum-99/tlaws pull request #1
Opened 2017-12-01 14:16 UTC by yuri-val

Prototype numbersapi

2017-12-01 14:36 UTC, zverok requested changes
Let's use this simple case to decide on two important things:
1. How should they be tested? At least some "sanity tests" are necessary (e.g. that it really successfully calls API not fails into 404 or something)
2. How should they be documented? So `Tlaws` user can look _somewhere_ for quick-reference for the API wrapper.

2017-12-01 14:36 UTC, zverok commented on lib/tlaws/numbers.rb
> +        param :numb, required: true
Let's keep it `number`, as in original docs. Two chars is not that much economy :)

2017-12-01 14:36 UTC, zverok commented on lib/tlaws/numbers.rb
> +        end
I believe the same endpoints repeats for one number (`[]`), and for the random number? Then let's make it DRY somehow (var.1: just do something like `%i[random, []].each do |namespace| ...`, var.2: try to introduce some solution in TLAW itself, that will allow to describe "shared endpoints" (like "shared examples" in RSpec), and then just `include_endpoints "number endpoints"` in DSL?)

2017-12-06 15:18 UTC, yuri-val commented on lib/tlaws/numbers.rb
> +        end
ok, got it

2017-12-06 15:20 UTC, yuri-val commented on lib/tlaws/numbers.rb
> +        param :numb, required: true
fix it

2017-12-06 15:26 UTC, yuri-val commented
@zverok, made some changes and added tests. Please review it.

2017-12-06 17:44 UTC, zverok requested changes

2017-12-06 17:44 UTC, zverok commented on lib/tlaws.rb
> +require_relative 'tlaws/numbers'
I don't think we should require them all here. Imagine some of the wrappers depend on other libraries (like nokogiri, or some geo-services, or even SQL databases) — we don't want all of it to be required at once. Typical use case is "I install entire Tlaws (say, 30 wrappers), but use only wrappers X and Y, so I require only them".

2017-12-06 17:44 UTC, zverok commented on lib/tlaws/numbers.rb
> +          if ns == :[]
`if`s look bad in declarative API description. TLAW supports (or intended to support, at least, check it!) continuing of descriptions in several blocks, so it should be written like this:
```ruby
namespace :[], '/numbers' do
  desc ...
  param ...
end

namespace :random do
  desc ...
  param ...
end

%i[[], random].each do |ns|
  namespace ns do
  ...other code that is common for both of them
  end
end
```

2017-12-06 17:44 UTC, zverok commented on lib/tlaws/numbers.rb
> +                * combined array   - numbers_api[[42..56, 77, 285, 770..777]].{type}
TLAW should support splat arguments (e.g. `[42..56, 77, 285, 770..777]` without second brackets), but currently it does not. Please add GitHub issue in TLAW repo, and implement it, or ask me to :)

2017-12-06 17:44 UTC, zverok commented on lib/tlaws/numbers.rb
> +            }
Non-keyword arguments don't seem like a good solution to me. `random(10)` intuitively reads like "random 0..10", not "random 10..Infinity". And the most useful call sequence ("give me random number less than some boundary") looks the most ugly: `random(nil, 10)`

2017-12-06 17:44 UTC, zverok commented on lib/tlaws/numbers.rb
> +            end_path += '&min={min}&max={max}'
Don't need it.

2017-12-06 17:44 UTC, zverok commented on lib/tlaws/numbers.rb
> +          endpoint :math, '/math' + end_path do
Please post TLAW GitHub issue for default always present GET argument.

2017-12-06 17:44 UTC, zverok commented on spec/tlaws_spec.rb
> +  let(:numbersapi){ Tlaws::Numbers.new	}
All of it should go to `spec/tlaws/numbers_spec.rb`

2017-12-06 17:44 UTC, zverok commented on spec/tlaws_spec.rb
> +	  it "get an answer" do
Something bad goes on with indentation here :) I strongly recommend add rubocop to the repo on the earliest stages ;)

2017-12-06 17:44 UTC, zverok commented on spec/tlaws_spec.rb
> +	end
**About testing strategy in total:** 
1. I believe that at least on early stages it should be as short "sanity checks" as possible, our primary goal is to not get bored with it, make sure it works.
2. Make it as readable and writable as possible, for easier update.
3. Make it fast.

So, the following seems to be a better strategy for this case (though not usual for RSpec in general):
```ruby
describe Tlaws::Numbers do
  let(:api) { described_class.new }
  it 'works' do
    expect(api[20].year).to include(something something)
    expect(api[20].day).to include(something something)
    expect(api.random(max: 3)).to ...
    expect(api.random(min: 200)).to ...
  end
end
```
WDYT?

...and add VCR, of course ;)

2025-07-21 06:39 UTC, closed without merging